import type { Metadata } from "next";
import { Montaga } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"

const montaga = Montaga({ weight: ["400"],subsets: ["latin"],variable: '--font-mont', });
const scaly = localFont({src: '../assets/ScalySans.otf', variable: '--font-scaly',})

export const metadata: Metadata = {
  title: "Casual Legends",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montaga.variable} ${scaly.variable} font-scaly`}>
      <main>
      <Navbar/>
      {children}
      <Footer/>
      </main>
        </body>
    </html>
  );
}
